plugins {
	id 'com.gradleup.shadow'
}

architectury {
	platformSetupLoomIde()
	fabric()
}

loom {
	accessWidenerPath = file("${project(':common').projectDir}/src/main/resources/legendarytooltips.accesswidener")
}

configurations {
	common {
		canBeResolved = true
		canBeConsumed = false
	}
	compileClasspath.extendsFrom common
	runtimeClasspath.extendsFrom common
	developmentFabric.extendsFrom common

	// Files in this configuration will be bundled into your mod using the Shadow plugin.
	// Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
	shadowBundle {
		canBeResolved = true
		canBeConsumed = false
	}
}

dependencies {
	implementation "net.fabricmc:fabric-loader:$rootProject.fabricLoaderVersion"
	implementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabricVersion"

	compileOnly "curse.maven:roughlyenoughitems-310111:8271476"
	implementation "curse.maven:justenoughitems-238222:8108850"

	common(project(path: ":common")) { transitive false }
	shadowBundle project(path: ':common', configuration: 'transformProductionFabric')
}

processResources {
	inputs.property 'version', project.version

	filesMatching('fabric.mod.json') {
		expand version: project.version
	}
}

jar {
	archiveClassifier = 'raw'
}

shadowJar {
	dependsOn(jar)
	mainSpec.sourcePaths.clear()
	from(zipTree(jar.archiveFile))

	configurations = [project.configurations.shadowBundle]
	archiveClassifier = null

	minimize {
		exclude(project(':common'))
	}

	destinationDirectory = file("$buildDir/../../output")
}
