plugins {
	id 'io.github.goooler.shadow' version '8.1.7' apply false
	id 'dev.architectury.loom' version '1.13-SNAPSHOT' apply false
	id 'architectury-plugin' version '3.4-SNAPSHOT'
}

apply plugin: 'architectury-plugin'

architectury {
	minecraft = project.minecraftVersion
}

allprojects {
	group = rootProject.group
	version = rootProject.modVersion
}

subprojects {
	apply plugin: 'dev.architectury.loom'
	apply plugin: 'architectury-plugin'

	base {
		archivesName = "$rootProject.name-$rootProject.minecraftVersion-$project.name"
	}

	repositories {
		maven {
			name = "CurseMaven"
			url = "https://www.cursemaven.com"
		}
	}

	dependencies {
		minecraft "net.minecraft:minecraft:$rootProject.minecraftVersion"
		mappings loom.officialMojangMappings()

		modImplementation files("../libs/Iceberg-1.21.4-common-1.2.10.jar")
		modImplementation files("../libs/Prism-1.21.4-common-1.0.10.jar")
	}

	java {
		sourceCompatibility = JavaVersion.VERSION_21
		targetCompatibility = JavaVersion.VERSION_21
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.release = 21
	}

	remapJar {
		destinationDirectory = file("$buildDir/../../output")
	}
}
