plugins {
	id "architectury-plugin" version "3.5-SNAPSHOT"
	id "dev.architectury.loom-no-remap" version "1.17-SNAPSHOT" apply false
	id 'com.gradleup.shadow' version '9.4.2' apply false
}

apply plugin: 'architectury-plugin'

architectury {
	minecraft = project.minecraftVersion
}

allprojects {
	group = rootProject.group
	version = rootProject.modVersion
}

subprojects {
	apply plugin: 'dev.architectury.loom-no-remap'
	apply plugin: 'architectury-plugin'

	base {
		archivesName = "$rootProject.name-$rootProject.minecraftVersion-$project.name"
	}

	repositories {
		maven {
			name = "CurseMaven"
			url = "https://www.cursemaven.com"
		}
	}

	dependencies {
		minecraft "net.minecraft:minecraft:$rootProject.minecraftVersion"

		implementation files("../libs/Iceberg-26.2-common-1.4.2.jar")
		implementation files("../libs/Prism-26.2-common-1.1.2.jar")
	}

	java {
		sourceCompatibility = JavaVersion.VERSION_25
		targetCompatibility = JavaVersion.VERSION_25
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.release = 25
	}

	plugins.withId('com.gradleup.shadow') {
		tasks.named('assemble').configure {
			dependsOn tasks.named('shadowJar')
		}
	}

	afterEvaluate {
		if (project.name == 'common') {
			tasks.named('jar').configure {
				archiveClassifier = null
				destinationDirectory = file("$buildDir/../../output")
			}
		}
	}
}
