# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

# Mod properties
name=${rootProject.name}
group=com.anthonyhilyard.${name.toLowerCase()}
author=anthonyhilyard
modVersion=1.6.1
enabledPlatforms=fabric,forge,neoforge
fabric.loom.disableRemappedVariants=true
loom.ignoreDependencyLoomVersionValidation=true

# Minecraft properties
minecraftVersion=26.1.2

# Dependencies
fabricLoaderVersion=0.19.2
fabricVersion=0.149.1+26.1.2
forgeVersion=26.1.2-64.0.8
neoforgeVersion=26.1.2.66-beta
