# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

# Mod properties
name=${rootProject.name}
group=com.anthonyhilyard.${name.toLowerCase()}
author=anthonyhilyard
modVersion=1.6.3
enabledPlatforms=fabric,forge,neoforge
fabric.loom.disableRemappedVariants=true
loom.ignoreDependencyLoomVersionValidation=true

# Minecraft properties
minecraftVersion=26.3

# Dependencies
fabricLoaderVersion=0.19.5
fabricVersion=0.161.0+26.3
forgeVersion=26.3-66.0.2
neoforgeVersion=26.3.0.7-beta
