# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

# Mod properties
name=${rootProject.name}
group=com.anthonyhilyard.${name.toLowerCase()}
author=anthonyhilyard
modVersion=1.5.0
enabledPlatforms=fabric,forge,neoforge
fabric.loom.disableRemappedVariants=true

# Minecraft properties
minecraftVersion=1.21.3

# Dependencies
fabricLoaderVersion=0.16.9
fabricVersion=0.110.0+1.21.3
forgeVersion=1.21.3-53.0.7
neoforgeVersion=21.3.11-beta
