architectury {
	common {
		clear()
		add(rootProject.enabledPlatforms.split(','))
		//forgeUsesMojangMappings = true
	}
}

loom {
	accessWidenerPath = file("src/main/resources/legendarytooltips.accesswidener")
}

dependencies {
	// We depend on Fabric Loader here to use the Fabric @Environment annotations,
	// which get remapped to the correct annotations on each platform.
	// Do NOT use other classes from Fabric Loader.
	modImplementation "net.fabricmc:fabric-loader:$rootProject.fabricLoaderVersion"
}
